# Generated by Django 3.0 on 2020-01-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0002_remove_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='os',
            field=models.CharField(choices=[('--', '--'), ('35', 'Linux/Unix'), ('30', 'Windows')], default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='purpose',
            field=models.CharField(choices=[('--', '--'), ('001', 'prd'), ('100', 'np'), ('111', 'test')], default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.CharField(choices=[('--', '--'), ('20', 'web'), ('21', 'app'), ('22', 'db'), ('23', 'storage')], default='--', max_length=10),
        ),
    ]
