# Generated by Django 3.0 on 2020-01-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0003_auto_20200123_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='tu',
            field=models.CharField(default='tu', max_length=2),
        ),
    ]
