# Generated by Django 3.0 on 2020-01-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0004_userdetails_tu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='title',
        ),
    ]
