# Generated by Django 3.0 on 2020-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0005_auto_20200123_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
