# Generated by Django 3.0 on 2020-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0006_userdetails_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='sequence',
            field=models.CharField(default='000', max_length=100),
        ),
    ]
