# Generated by Django 3.0 on 2020-01-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0007_auto_20200123_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='os',
            new_name='OS',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='purpose',
            field=models.CharField(choices=[('--', '--'), ('001', 'Production'), ('100', 'Non-Production'), ('111', 'Test')], default='--', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.CharField(choices=[('--', '--'), ('20', 'Web'), ('21', 'Application'), ('22', 'Database'), ('23', 'Storage')], default='--', max_length=10),
        ),
    ]
