# Generated by Django 3.0 on 2020-01-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0008_auto_20200127_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='ServerDetails',
        ),
    ]
