# Generated by Django 3.0 on 2020-01-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0012_auto_20200127_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Windows_np_web',
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='classification',
            field=models.CharField(default='', max_length=15),
        ),
    ]
