# Generated by Django 3.0 on 2020-01-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0014_auto_20200129_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='alias',
            field=models.CharField(default='tyler', max_length=15),
        ),
    ]
