# Generated by Django 3.0 on 2020-01-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0015_serverdetails_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdetails',
            name='alias',
        ),
    ]
