# Generated by Django 3.0 on 2020-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0016_remove_serverdetails_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='serverIdent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
