# Generated by Django 3.0 on 2020-01-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='gender',
        ),
    ]
