# Generated by Django 3.0 on 2020-01-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0009_auto_20200127_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Windows_np_web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
