# Generated by Django 3.0 on 2020-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0010_windows_np_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='serverName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
