# Generated by Django 3.0 on 2020-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0011_serverdetails_servername'),
    ]

    operations = [
        migrations.AddField(
            model_name='windows_np_web',
            name='OS',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='windows_np_web',
            name='purpose',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='windows_np_web',
            name='role',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='windows_np_web',
            name='sequence',
            field=models.CharField(default='000', max_length=100),
        ),
        migrations.AddField(
            model_name='windows_np_web',
            name='serverName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='windows_np_web',
            name='tu',
            field=models.CharField(default='tu', max_length=2),
        ),
    ]
