# Generated by Django 3.0 on 2020-01-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0013_auto_20200127_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverdetails',
            old_name='classification',
            new_name='ident',
        ),
    ]
